Tarea3prog/Models/CategoriaEmpleado.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Tarea3prog.Models
{
    public enum CategoriaEmpleado
    {
        Gerencial,                   //Reciben un bono del 50% de su salario    
        Administrativo,             //Reciben un bono del 25% de su salario
        Operativo                  //Reciben un bono del 10% de su salario
    }
}

Tarea3prog/Models/Empelado.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Threading;
using System.Threading.Tasks;

namespace Tarea3prog.Models
{
    public class Empleado
    {
        public Guid Id { get; set; }

        public int Cedula { get; set; }

        public string Nombre { get; set; }

        public string Apellido { get; set; }


        public string Email { get; set; }

        public int Telefono { get; set; }

        public string Departamento { get; set; }

        public string Cargo { get; set; }

        public CategoriaEmpleado CategoriaEmpleado { get; set; }

        public decimal Salario { get; set; }

        public void CalcularBono()
        {
            switch (CategoriaEmpleado)
            {
                case CategoriaEmpleado.Gerencial: Salario = Salario * 1.5M;
                    break;

                case CategoriaEmpleado.Administrativo: Salario = Salario * 1.25M;
                    break;

                case CategoriaEmpleado.Operativo: Salario = Salario * 1.10M;
                    break;

            }
        }
    





}
    }

Tarea3prog/Models/ManejoArchivo.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using Tarea3prog.Models;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.IO;
using System.Threading;
using System.Threading.Tasks;

namespace Tarea3prog.Models
{
       public class ManejoArchivo
        {
          
            private static ManejoArchivo instance = null;
            public static ManejoArchivo GetInstance
            {
                get
                {
                    if (instance == null)
                        instance = new ManejoArchivo();
                    return instance;
                }
            }
        private ManejoArchivo()
            {
                
            }
            public void Guardar(Empleado data)
            {
            data.Id = Guid.NewGuid();

            var listaEmpleados = new List<Empleado>();

            listaEmpleados.Add(data);

            string jsonString = JsonSerializer.Serialize(listaEmpleados);



            using (StreamWriter writer = new StreamWriter("ListaEmp"))
            {
                writer.WriteLine(jsonString);
            }
            }
        }

    


        
}

Tarea3prog/Controllers/EmpleadoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Tarea3prog.Models;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.IO;



namespace Tarea3prog.Controllers
{
    public class EmpleadoController : Controller
    {
        // GET: Empleado
        public ActionResult Inicio()
        {
            return View();
        }




        public ActionResult Datos()
        {

            return View();
        }


        public ActionResult Resultados(Empleado data)
        {
            var manejoarchivo = ManejoArchivo.GetInstance;

            manejoarchivo.Guardar(data);

            return View(data);

        }
    }
}

Tarea3prog/Views/Empleado/Datos.cshtml
@model Tarea3prog.Models.Empleado

@{
    ViewBag.Title = "Datos";
}




<h2>Datos</h2>
<form action="Resultados" method="post">

    <input type="number" name="id" class="form-control" placeholder="Inserte su Id" />
    <input type="number" name="cedula" class="form-control" placeholder="Inserte su Cedula" required />
    <input type="text" name="nombre" class="form-control" placeholder="Inserte su Nombre" required />
    <input type="text" name="apellido" class="form-control" placeholder="Inserte su Apellido" required />
    <input type="text" name="email" class="form-control" placeholder="Inserte su Email" />
    <input type="number" name="telefono" class="form-control" placeholder="Inserte su Telefono" />
    <input type="text" name="departamento" class="form-control" placeholder="Inserte su Departamento" />
    <input type="text" name="cargo" class="form-control" placeholder="Inserte su Cargo" />



    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.Id)
            <div class="form-group">
                @Html.LabelFor(model => model.CategoriaEmpleado, htmlAttributes: new { @class = "control-label col-md-2" })


                <div class="col-md-10">
                    @Html.EnumDropDownListFor(model => model.CategoriaEmpleado, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.CategoriaEmpleado, "", new { @class = "text-danger" })
                </div>

            </div>
        </div>

    }







    <input type="submit" value="Enviar" />








</form>

Tarea3prog/Views/Empleado/Inicio.cshtml
@{
    ViewBag.Title = "Inicio";
}




<h2>Bienvenidos a la Plataforma</h2>

<a href="Empleado/Datos" class="btn btn-primary" >Registrar Datos de Empleados</a>

Tarea3prog/Views/Empleado/Resultados.cshtml
@model Tarea3prog.Models.Empleado

@{
    ViewBag.Title = "Resultados";
}

<h2>Datos</h2>
<label>Id: @Model.Id</label>
<label>Cedula: @Model.Cedula</label>
<label>Nombre: @Model.Nombre</label>
<label>Apellido: @Model.Apellido</label>
<label>Email: @Model.Email</label>
<label>Telefono: @Model.Telefono</label>
<label>Departamento: @Model.Departamento</label>
<label>Cargo: @Model.Cargo</label>

Tarea3prog/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Mi aplicación ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("TareaProg3", "Inicio", "Empleado", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Empleado", "Inicio", "Empleado")</li>
                    <li>@Html.ActionLink("Datos", "Datos", "Empleado")</li>
                    <li>@Html.ActionLink("Resultados", "Resultados", "Empleado")</li>

                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Mi aplicación ASP.NET</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
 --------------
    @RenderSection("scripts", required: false)
</body>
    </html>